import { Roboto } from "next/font/google";
import "./globals.css";
import { useStore } from "zustand";
import Login from "./ui/Login";

const roboto = Roboto({ subsets: ["latin"], weight: '300'});

export const metadata = {
  title: "Telegram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
